language: ruby
rvm:
  - 2.1.2
  - 2.1.0
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
addons:
  postgresql: "9.2"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
install: gem install rails
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec