language: ruby
rvm:
  - 2.1.2
  - 2.1.0
  - jruby-18mode
  - jruby-19mode
  - rbx-2
  - ruby-head
  - jruby-head
  - ree
  - "1.8.7"
  - "1.9.2"
  - "1.9.3"
  - rbx
addons:
  postgresql: "9.2"
before_script:
  - psql -c 'create database travis_ci_test;' -U postgres
# uncomment this line if your project needs to run something other than `rake`:
# script: bundle exec rspec spec